--Adding MEAL_TYPE Values into H2 database
DROP TABLE IF EXISTS MEAL_TYPE;
CREATE TABLE MEAL_TYPE (id INT AUTO_INCREMENT  PRIMARY KEY, TYPE VARCHAR(15) NOT NULL);
INSERT INTO MEAL_TYPE VALUES(1, 'Breakfast');
INSERT INTO MEAL_TYPE VALUES(2, 'Dinner');
INSERT INTO MEAL_TYPE VALUES(3, 'Lunch');
INSERT INTO MEAL_TYPE VALUES(4, 'Dessert');
INSERT INTO MEAL_TYPE VALUES(5, 'Not Applicable');

--Adding WEEKDAY Values into H2 database
DROP TABLE IF EXISTS WEEKDAY;
CREATE TABLE WEEKDAY (id INT PRIMARY KEY, DAY VARCHAR(10) NOT NULL);
INSERT INTO WEEKDAY VALUES(1, 'Monday');
INSERT INTO WEEKDAY VALUES(2, 'Tuesday');
INSERT INTO WEEKDAY VALUES(3, 'Wednesday');
INSERT INTO WEEKDAY VALUES(4, 'Thursday');
INSERT INTO WEEKDAY VALUES(5, 'Friday');
INSERT INTO WEEKDAY VALUES(6, 'Saturday');
INSERT INTO WEEKDAY VALUES(7, 'Sunday');
